# Pandas

###### É uma biblioteca criada para manibular dados estruturado,tem uma importante função para indexação.

###### Utilizada na fase de preparação dos dados.

###### Funciona muito bem com o NumPy

##### Estruras de sereis e Dataframe

###### Series é um array unidimensional que contém um array de dados e um array de labels, chamado de Indice.

###### Dataframes representam uma estrutura tabular semelhante a estrutura de uma planilha de Exel,contendo uma coleção de colunas em que cada uma pode ser um diferente tipo de valor(número, string,etc...).

###### Os dataframes possuem index e linhas, são armazenados em um ou mais blocos bidimensionais, ao invés de listas, dicionários ou alguma outra estrutura de array.

In [1]:
# criando uma serie e especificando os indices
from pandas import Series


In [2]:
#Importando o pacote pandas inteiro
import pandas as pd


In [3]:
pd.__version__

'0.25.2'

In [4]:
#Criando uma série sem especifica os indices
obj = Series([32, 82, -36, 16])

In [5]:
obj

0    32
1    82
2   -36
3    16
dtype: int64

In [6]:
type(obj)

pandas.core.series.Series

In [7]:
# Estraindo valores da Série
obj.values

array([ 32,  82, -36,  16], dtype=int64)

In [8]:
# Estraindo indices da Série
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
#Criando uma série especifica os indices
obj2 = Series([36, 28, -63, 61], index = ['a', 'b', 'c', 'd'])

In [10]:
obj2

a    36
b    28
c   -63
d    61
dtype: int64

In [11]:
obj2.values

array([ 36,  28, -63,  61], dtype=int64)

In [12]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
obj2 [obj2 < 50]

a    36
b    28
c   -63
dtype: int64

In [14]:
# Mostrando o valor do Index
obj2['b']

28

In [15]:
# Verificando se possui 'd' no obj2
'd' in obj2

True

In [16]:
# Criando uma Série de dados passando um dicionário como parâmetro
dict = {'uva':43, 'morango':64, 'kiwi':78, 'tangerina':85}

In [17]:
#Criando uma Série a partir de um dicionário
obj3 = Series(dict)

In [18]:
obj3

uva          43
morango      64
kiwi         78
tangerina    85
dtype: int64

In [19]:
type(obj3)

pandas.core.series.Series

In [20]:
# Criando uma lista
frutas = ['uva', 'morango', 'kiwi', 'laranja']

In [21]:
# Criando uma série usando uma lista como indice
obj4 = Series(dict, index = frutas)

In [22]:
obj4

uva        43.0
morango    64.0
kiwi       78.0
laranja     NaN
dtype: float64

In [23]:
# Perguntando se tem um objeto nulo
pd.isnull(obj4)

uva        False
morango    False
kiwi       False
laranja     True
dtype: bool

In [24]:
# Perguntando se tem um objeto não nulo
pd.notnull(obj4)

uva         True
morango     True
kiwi        True
laranja    False
dtype: bool

In [25]:
# Perguntando se tem um objeto nulo com o proprio objeto 
obj4.isnull()

uva        False
morango    False
kiwi       False
laranja     True
dtype: bool

In [26]:
# Concatenando Series
obj3 + obj4

kiwi         156.0
laranja        NaN
morango      128.0
tangerina      NaN
uva           86.0
dtype: float64

In [27]:
obj4.name = 'ListaDeFrutas'

In [28]:
obj4

uva        43.0
morango    64.0
kiwi       78.0
laranja     NaN
Name: ListaDeFrutas, dtype: float64

In [29]:
obj4.index.name = "frutas"

In [30]:
obj4

frutas
uva        43.0
morango    64.0
kiwi       78.0
laranja     NaN
Name: ListaDeFrutas, dtype: float64

### Dataframes

In [31]:
# Importando data frames
from pandas import DataFrame

In [32]:
data = {'Cidade' : ['Jaguaribe','Pereiro','Fortaleza','Icó','orós'],
        'Ano' : [1999,2001,2002,2008,2019],
        'População' : [1.3,1.4,1.5,2.5,3.6]}

In [33]:
# Alimentando o data frame do pandas
frame = DataFrame(data)

In [34]:
frame

Cidade   Ano  População
0  Jaguaribe  1999        1.3
1    Pereiro  2001        1.4
2  Fortaleza  2002        1.5
3        Icó  2008        2.5
4       orós  2019        3.6

In [35]:
type(frame)

pandas.core.frame.DataFrame

In [36]:
# Determinando o nome das colunas
DataFrame(data,columns = ['Ano', 'Cidade', 'População'])

Ano     Cidade  População
0  1999  Jaguaribe        1.3
1  2001    Pereiro        1.4
2  2002  Fortaleza        1.5
3  2008        Icó        2.5
4  2019       orós        3.6

In [37]:
# Criando outro dataframe com os mesmos dados anteriores mas adicionando uma coluna 
frame2 = DataFrame(data,columns = ['Ano', 'Cidade', 'População', 'Débito'],
          index = ['Um', 'Dois', 'Três', 'Quatro','Cinco'])

In [38]:
frame2

Ano     Cidade  População Débito
Um      1999  Jaguaribe        1.3    NaN
Dois    2001    Pereiro        1.4    NaN
Três    2002  Fortaleza        1.5    NaN
Quatro  2008        Icó        2.5    NaN
Cinco   2019       orós        3.6    NaN

In [39]:
frame2['Cidade'] = frame2['Cidade'].astype('str')

In [40]:
frame2 < 5

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
frame2.Ano

In [ ]:
# Imprimindo os índices
frame2.index

In [41]:
# Imprimindo as colunas
frame2.columns

Index(['Ano', 'Cidade', 'População', 'Débito'], dtype='object')

In [42]:
# Imprimindo os valores
frame2.values

array([[1999, 'Jaguaribe', 1.3, nan],
       [2001, 'Pereiro', 1.4, nan],
       [2002, 'Fortaleza', 1.5, nan],
       [2008, 'Icó', 2.5, nan],
       [2019, 'orós', 3.6, nan]], dtype=object)

In [43]:
# Imprimir os índices antes de determinado ponto
frame2[ :2]

Ano     Cidade  População Débito
Um    1999  Jaguaribe        1.3    NaN
Dois  2001    Pereiro        1.4    NaN

### Usando NumPy e Pandas

In [60]:
# Importando o NumPy
import numpy as np

In [61]:
# Utilizando NumPy para alimentar a coluna do dataframe
frame2['Débito'] = np.arange(5.)

In [62]:
frame2

Ano     Cidade  População  Débito
Um      1999  Jaguaribe        1.3     0.0
Dois    2001    Pereiro        1.4     1.0
Três    2002  Fortaleza        1.5     2.0
Quatro  2008        Icó        2.5     3.0
Cinco   2019       orós        3.6     4.0

In [63]:
frame2.values

array([[1999, 'Jaguaribe', 1.3, 0.0],
       [2001, 'Pereiro', 1.4, 1.0],
       [2002, 'Fortaleza', 1.5, 2.0],
       [2008, 'Icó', 2.5, 3.0],
       [2019, 'orós', 3.6, 4.0]], dtype=object)

In [64]:
# Resumo do Dataframe
frame2.describe()

Ano  População    Débito
count     5.000000   5.000000  5.000000
mean   2005.800000   2.060000  2.000000
std       8.105554   0.986408  1.581139
min    1999.000000   1.300000  0.000000
25%    2001.000000   1.400000  1.000000
50%    2002.000000   1.500000  2.000000
75%    2008.000000   2.500000  3.000000
max    2019.000000   3.600000  4.000000

In [65]:
frame2['Dois':'Quatro']

Ano     Cidade  População  Débito
Dois    2001    Pereiro        1.4     1.0
Três    2002  Fortaleza        1.5     2.0
Quatro  2008        Icó        2.5     3.0

In [68]:
frame2['Cidade'] < 5

TypeError: '<' not supported between instances of 'str' and 'int'

#### Localizando Registros Dentro do Dataframe

In [51]:
frame2.loc['Quatro']

Ano          2008
Cidade        Icó
População     2.5
Débito          3
Name: Quatro, dtype: object

In [52]:
frame2.iloc[2]

Ano               2002
Cidade       Fortaleza
População          1.5
Débito               2
Name: Três, dtype: object

### Ivertendo as Colunas e Índices

In [53]:
# Criando um dicionário
visitas = {'dias':[1,2,3,4,5,6,7],
        'visitantes':[45,53,65,77,78,81,90],
        'taxas':[11,12,13,21,22,25,30]}


In [54]:
# Convertendo Dicionário eem dataframe
df = pd.DataFrame(visitas)

In [55]:
df

dias  visitantes  taxas
0     1          45     11
1     2          53     12
2     3          65     13
3     4          77     21
4     5          78     22
5     6          81     25
6     7          90     30

In [56]:
# Visualizando uma coliuna index
print(df.set_index('dias'))

      visitantes  taxas
dias                   
1             45     11
2             53     12
3             65     13
4             77     21
5             78     22
6             81     25
7             90     30


In [57]:
print(df.head())

   dias  visitantes  taxas
0     1          45     11
1     2          53     12
2     3          65     13
3     4          77     21
4     5          78     22


In [58]:
print(df['visitantes'])

0    45
1    53
2    65
3    77
4    78
5    81
6    90
Name: visitantes, dtype: int64


In [59]:
print(df[['visitantes','taxas']])

   visitantes  taxas
0          45     11
1          53     12
2          65     13
3          77     21
4          78     22
5          81     25
6          90     30
